<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<!--
Promise
2020年3月16日18:50:31
-->

</body>
</html>


<script type="text/javascript">

    let log = (...filed) => {
        const { log } = console
        log('\t', ...filed)
    }

    /*
    1）对象的状态不受外界影响。Promise对象代表一个异步操作，有三种状态：pending（进行中）、fulfilled（已成功）和rejected（已失败）。
    只有异步操作的结果，可以决定当前是哪一种状态，任何其他操作都无法改变这个状态。

    （2）一旦状态改变，就不会再变，任何时候都可以得到这个结果。

     */
/*    const promise = new Promise(function(resolve, reject) {
        // ... some code
        if (true){
            console.log('resolve')
            resolve(value);
        } else {
            console.log('reject')
            reject();
        }
    });

    promise.then(function(value) {
        // success
        console.log('then',value)
    }, function(error) {
        // failure
        console.log('fail')
    });

    // doubt: 不懂
    // 输出为， resolve fail


    //  第二个练习

    // todo: 复习window 的语法： https://developer.mozilla.org/zh-CN/docs/Web/API/Window/setTimeout
    function timeout(ms) {
        return new Promise((resolve, reject) => {
            setTimeout(resolve, ms, 'done'); // 这个函数是延迟多少毫秒后，执行前面的方法，返回后面的值
        });
    }

    timeout(100).then((value) => {
        console.log(value);
    });*/

    // 练习三: promise新建后，会立即执行
    let promise3 = new Promise(function(resolve, reject) {
        console.log('Promise');
        resolve();
    });

    promise3.then(function() {
        console.log('resolved.');
    });

    console.log('Hi!');
    setTimeout(() => {console.log('in here')},2000);
    console.log('Hi3!');
    // 上面代码中，Promise 新建后立即执行，所以首先输出的是Promise。
    // 然后，then方法指定的回调函数，将在当前脚本所有同步任务执行完才会执行，所以resolved最后输出。

    // Promise
    // Hi!
    // Hi3!
    // resolved
    // in here



    // 练习4：
    const p1 = new Promise(function (resolve, reject) {
        setTimeout(() => reject(new Error('fail')), 3000)
    })

    const p2 = new Promise(function (resolve, reject) {
        setTimeout(() => resolve(p1), 1000)
    })

    p2
        .then(result => console.log(result))
        .catch(error => console.log(error))
    // Error: fail


    // 练习5： 调用resolve或者reject并不会终结Promise的参数函数的执行
    new Promise((resolve, reject) => {
        resolve(1);
        console.log(2);
    }).then(r => {
        console.log(r);
    });
    // 2
    // 1

    // 所以最好这样
    new Promise((resolve, reject) => {
        return resolve(1);
        // 后面的语句不会执行
        console.log(2);
    })




</script>
